install:
  - curl -O http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - tar xfz rust-nightly-x86_64-unknown-linux-gnu.tar.gz

script:
  - rust-nightly-x86_64-unknown-linux-gnu/bin/rustc --version
  - RUSTC=rust-nightly-x86_64-unknown-linux-gnu/bin/rustc make test

notifications:
  email:
    - michaelneuma@gmail.com
